//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class ConceptoVenta_DE : EntityId
    {
    	//Fields
        protected internal string _Codigo;
        public virtual string Codigo
    	{
    	    get { return _Codigo; }
    	    set { if (value != _Codigo) { _Codigo = value; OnPropertyChanged("Codigo"); } }
        }	
        protected internal string _Nombre;
        public virtual string Nombre
    	{
    	    get { return _Nombre; }
    	    set { if (value != _Nombre) { _Nombre = value; OnPropertyChanged("Nombre"); } }
        }	
        protected internal Nullable<bool> _Activo;
        public virtual Nullable<bool> Activo
    	{
    	    get { return _Activo; }
    	    set { if (value != _Activo) { _Activo = value; OnPropertyChanged("Activo"); } }
        }	
        protected internal Nullable<bool> _EsDefault;
        public virtual Nullable<bool> EsDefault
    	{
    	    get { return _EsDefault; }
    	    set { if (value != _EsDefault) { _EsDefault = value; OnPropertyChanged("EsDefault"); } }
        }	
    
    	//ForeignKeys
    
    	//Parents
    
    	//Childs
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class ConceptoVenta_BE : ConceptoVenta_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class ConceptoVenta_DA : AccessEntityId
    {
    	public  ConceptoVenta_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new ConceptoVenta_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            ConceptoVenta_DE be = (ConceptoVenta_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo", System.Data.DbType.String, be.Codigo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_default", System.Data.DbType.Boolean, be.EsDefault, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            ConceptoVenta_DE be = (ConceptoVenta_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramReader[TableColumn("codigo")]);
    		be._Nombre = Conversion.To<string>(paramReader[TableColumn("nombre")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramReader[TableColumn("activo")]);
    		be._EsDefault = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_default")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            ConceptoVenta_DE be = (ConceptoVenta_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramRow[TableColumn("codigo")]);
    		be._Nombre = Conversion.To<string>(paramRow[TableColumn("nombre")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramRow[TableColumn("activo")]);
    		be._EsDefault = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_default")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            ConceptoVenta_DE be = (ConceptoVenta_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramParameters[TableParameter("codigo")].Value);
    		be._Nombre = Conversion.To<string>(paramParameters[TableParameter("nombre")].Value);
    		be._Activo = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("activo")].Value);
    		be._EsDefault = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_default")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            ConceptoVenta_DE be = (ConceptoVenta_DE)paramDE;
    
    		be._Codigo = null;
    		be._Nombre = null;
    		be._Activo = null;
    		be._EsDefault = null;
      
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class ConceptoVenta_BA : ConceptoVenta_DA
    {
    	public  ConceptoVenta_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new ConceptoVenta_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class ConceptoVenta_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new ConceptoVenta_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            ConceptoVenta_BE be = (ConceptoVenta_BE)paramDE;
    
            if (string.IsNullOrWhiteSpace(be.Codigo))
            {
                paramField = "Codigo";
                paramMessage = LibraryFramework.V0003_CodeEmpty;
    
                return false;
            }
    		
            if (Count(new ConceptoVenta_BE() { Codigo = be.Codigo }) > 0)
            {
                paramField = "Codigo";
                paramMessage = LibraryFramework.V0004_CodeExists;
                return false;
            }		
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            ConceptoVenta_BE be = (ConceptoVenta_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		ConceptoVenta_BE be = (ConceptoVenta_BE)paramDE;
    
    		foreach (ConceptoVenta_BE e in new ConceptoVenta_FL().LoadConvert(new ConceptoVenta_FL().Convert(be), 1))
    		{
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    	
    	protected override byte SaveParent(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            ConceptoVenta_BE be = (ConceptoVenta_BE)paramDE;
    
            byte ret = 1;
    
    				
            if (ret == 1)
            {		
    		}
    
            return ret;
        }
        protected override byte SaveDetails(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            ConceptoVenta_BE be = (ConceptoVenta_BE)paramDE;
    
            byte ret = 1;
    
            if (ret == 1)
            {        
    		} 
    		
            if (ret == 1)
            {		}		
            
            return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class ConceptoVenta_BL : ConceptoVenta_DL
    {
        protected override Access GetDA()
        {
            return new ConceptoVenta_BA(TableName, ConnectionStringName);
        }		
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class ConceptoVenta_JE : EnumerateId
    {
        public virtual Filter<string> Codigo { get; set; }
        public virtual Filter<string> Nombre { get; set; }
        public virtual Filter<Nullable<bool>> Activo { get; set; }
        public virtual Filter<Nullable<bool>> EsDefault { get; set; }
    
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class ConceptoVenta_FE : ConceptoVenta_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class ConceptoVenta_JA : AccessEnumerateId
    {	
    	public  ConceptoVenta_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new ConceptoVenta_DE();
        }
    	protected override Access GetDA()
        {
            return new ConceptoVenta_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            ConceptoVenta_JE be = (ConceptoVenta_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo", System.Data.DbType.String, be.Codigo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_default", System.Data.DbType.Boolean, be.EsDefault, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            ConceptoVenta_FE be = (ConceptoVenta_FE)paramDE;
    		
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		ConceptoVenta_FE be = (ConceptoVenta_FE)paramDE;	
    
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class ConceptoVenta_FA : ConceptoVenta_JA
    {	
    	public  ConceptoVenta_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new ConceptoVenta_BE();
        }
    	protected override Access GetDA()
        {
            return new ConceptoVenta_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class ConceptoVenta_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new ConceptoVenta_JA(TableName, ConnectionStringName);
        }
    	
    	public List<ConceptoVenta_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as ConceptoVenta_BE);
        }
    	public ConceptoVenta_FE Convert(ConceptoVenta_BE paramDE)
        {
            ConceptoVenta_FE be = new ConceptoVenta_FE();
    
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
    		be.Codigo = new Filter<string>(paramDE.Codigo);
    		be.Nombre = new Filter<string>(paramDE.Nombre);
    		be.Activo = new Filter<Nullable<bool>>(paramDE.Activo);
    		be.EsDefault = new Filter<Nullable<bool>>(paramDE.EsDefault);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class ConceptoVenta_FL : ConceptoVenta_JL
    {
    	protected override Access GetDA()
        {
            return new ConceptoVenta_FA(TableName, ConnectionStringName);
        }
    }
}

