//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class Detracciones_DE : EntityId
    {
    	//Fields
        protected internal string _Codigo;
        public virtual string Codigo
    	{
    	    get { return _Codigo; }
    	    set { if (value != _Codigo) { _Codigo = value; OnPropertyChanged("Codigo"); } }
        }	
        protected internal string _Nombre;
        public virtual string Nombre
    	{
    	    get { return _Nombre; }
    	    set { if (value != _Nombre) { _Nombre = value; OnPropertyChanged("Nombre"); } }
        }	
        protected internal Nullable<decimal> _Porcentaje;
        public virtual Nullable<decimal> Porcentaje
    	{
    	    get { return _Porcentaje; }
    	    set { if (value != _Porcentaje) { _Porcentaje = value; OnPropertyChanged("Porcentaje"); } }
        }	
        protected internal Nullable<decimal> _TopeImporte;
        public virtual Nullable<decimal> TopeImporte
    	{
    	    get { return _TopeImporte; }
    	    set { if (value != _TopeImporte) { _TopeImporte = value; OnPropertyChanged("TopeImporte"); } }
        }	
        protected internal Nullable<bool> _Activo;
        public virtual Nullable<bool> Activo
    	{
    	    get { return _Activo; }
    	    set { if (value != _Activo) { _Activo = value; OnPropertyChanged("Activo"); } }
        }	
    
    	//ForeignKeys
    
    	//Parents
    
    	//Childs
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class Detracciones_BE : Detracciones_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class Detracciones_DA : AccessEntityId
    {
    	public  Detracciones_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new Detracciones_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Detracciones_DE be = (Detracciones_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo", System.Data.DbType.String, be.Codigo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<decimal>>(fields, "porcentaje", System.Data.DbType.Decimal, be.Porcentaje, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<decimal>>(fields, "tope_importe", System.Data.DbType.Decimal, be.TopeImporte, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            Detracciones_DE be = (Detracciones_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramReader[TableColumn("codigo")]);
    		be._Nombre = Conversion.To<string>(paramReader[TableColumn("nombre")]);
    		be._Porcentaje = Conversion.To<Nullable<decimal>>(paramReader[TableColumn("porcentaje")]);
    		be._TopeImporte = Conversion.To<Nullable<decimal>>(paramReader[TableColumn("tope_importe")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramReader[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            Detracciones_DE be = (Detracciones_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramRow[TableColumn("codigo")]);
    		be._Nombre = Conversion.To<string>(paramRow[TableColumn("nombre")]);
    		be._Porcentaje = Conversion.To<Nullable<decimal>>(paramRow[TableColumn("porcentaje")]);
    		be._TopeImporte = Conversion.To<Nullable<decimal>>(paramRow[TableColumn("tope_importe")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramRow[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            Detracciones_DE be = (Detracciones_DE)paramDE;
    
    		be._Codigo = Conversion.To<string>(paramParameters[TableParameter("codigo")].Value);
    		be._Nombre = Conversion.To<string>(paramParameters[TableParameter("nombre")].Value);
    		be._Porcentaje = Conversion.To<Nullable<decimal>>(paramParameters[TableParameter("porcentaje")].Value);
    		be._TopeImporte = Conversion.To<Nullable<decimal>>(paramParameters[TableParameter("tope_importe")].Value);
    		be._Activo = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("activo")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            Detracciones_DE be = (Detracciones_DE)paramDE;
    
    		be._Codigo = null;
    		be._Nombre = null;
    		be._Porcentaje = null;
    		be._TopeImporte = null;
    		be._Activo = null;
      
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class Detracciones_BA : Detracciones_DA
    {
    	public  Detracciones_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Detracciones_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class Detracciones_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new Detracciones_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            Detracciones_BE be = (Detracciones_BE)paramDE;
    
            if (string.IsNullOrWhiteSpace(be.Codigo))
            {
                paramField = "Codigo";
                paramMessage = LibraryFramework.V0003_CodeEmpty;
    
                return false;
            }
    		
            if (Count(new Detracciones_BE() { Codigo = be.Codigo }) > 0)
            {
                paramField = "Codigo";
                paramMessage = LibraryFramework.V0004_CodeExists;
                return false;
            }		
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            Detracciones_BE be = (Detracciones_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		Detracciones_BE be = (Detracciones_BE)paramDE;
    
    		foreach (Detracciones_BE e in new Detracciones_FL().LoadConvert(new Detracciones_FL().Convert(be), 1))
    		{
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    	
    	protected override byte SaveParent(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            Detracciones_BE be = (Detracciones_BE)paramDE;
    
            byte ret = 1;
    
    				
            if (ret == 1)
            {		
    		}
    
            return ret;
        }
        protected override byte SaveDetails(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            Detracciones_BE be = (Detracciones_BE)paramDE;
    
            byte ret = 1;
    
            if (ret == 1)
            {        
    		} 
    		
            if (ret == 1)
            {		}		
            
            return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class Detracciones_BL : Detracciones_DL
    {
        protected override Access GetDA()
        {
            return new Detracciones_BA(TableName, ConnectionStringName);
        }		
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class Detracciones_JE : EnumerateId
    {
        public virtual Filter<string> Codigo { get; set; }
        public virtual Filter<string> Nombre { get; set; }
        public virtual Filter<Nullable<decimal>> Porcentaje { get; set; }
        public virtual Filter<Nullable<decimal>> TopeImporte { get; set; }
        public virtual Filter<Nullable<bool>> Activo { get; set; }
    
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class Detracciones_FE : Detracciones_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class Detracciones_JA : AccessEnumerateId
    {	
    	public  Detracciones_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Detracciones_DE();
        }
    	protected override Access GetDA()
        {
            return new Detracciones_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Detracciones_JE be = (Detracciones_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo", System.Data.DbType.String, be.Codigo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<decimal>>(fields, "porcentaje", System.Data.DbType.Decimal, be.Porcentaje, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<decimal>>(fields, "tope_importe", System.Data.DbType.Decimal, be.TopeImporte, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Detracciones_FE be = (Detracciones_FE)paramDE;
    		
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		Detracciones_FE be = (Detracciones_FE)paramDE;	
    
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class Detracciones_FA : Detracciones_JA
    {	
    	public  Detracciones_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Detracciones_BE();
        }
    	protected override Access GetDA()
        {
            return new Detracciones_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class Detracciones_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new Detracciones_JA(TableName, ConnectionStringName);
        }
    	
    	public List<Detracciones_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as Detracciones_BE);
        }
    	public Detracciones_FE Convert(Detracciones_BE paramDE)
        {
            Detracciones_FE be = new Detracciones_FE();
    
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
    		be.Codigo = new Filter<string>(paramDE.Codigo);
    		be.Nombre = new Filter<string>(paramDE.Nombre);
    		be.Porcentaje = new Filter<Nullable<decimal>>(paramDE.Porcentaje);
    		be.TopeImporte = new Filter<Nullable<decimal>>(paramDE.TopeImporte);
    		be.Activo = new Filter<Nullable<bool>>(paramDE.Activo);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class Detracciones_FL : Detracciones_JL
    {
    	protected override Access GetDA()
        {
            return new Detracciones_FA(TableName, ConnectionStringName);
        }
    }
}

