//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class Documentos_Venta_DE : EntityId
    {
        protected internal string _Nombre;
        public virtual string Nombre
    	{
    	    get { return _Nombre; }
    	    set { if (value != _Nombre) { _Nombre = value; OnPropertyChanged("Nombre"); } }
        }	
        protected internal string _Abreviado;
        public virtual string Abreviado
    	{
    	    get { return _Abreviado; }
    	    set { if (value != _Abreviado) { _Abreviado = value; OnPropertyChanged("Abreviado"); } }
        }	
        protected internal string _CodigoTributario;
        public virtual string CodigoTributario
    	{
    	    get { return _CodigoTributario; }
    	    set { if (value != _CodigoTributario) { _CodigoTributario = value; OnPropertyChanged("CodigoTributario"); } }
        }	
        protected internal Nullable<bool> _Activo;
        public virtual Nullable<bool> Activo
    	{
    	    get { return _Activo; }
    	    set { if (value != _Activo) { _Activo = value; OnPropertyChanged("Activo"); } }
        }	
        protected internal Nullable<bool> _EsNotaDebito;
        public virtual Nullable<bool> EsNotaDebito
    	{
    	    get { return _EsNotaDebito; }
    	    set { if (value != _EsNotaDebito) { _EsNotaDebito = value; OnPropertyChanged("EsNotaDebito"); } }
        }	
        protected internal Nullable<bool> _CalculaIgv;
        public virtual Nullable<bool> CalculaIgv
    	{
    	    get { return _CalculaIgv; }
    	    set { if (value != _CalculaIgv) { _CalculaIgv = value; OnPropertyChanged("CalculaIgv"); } }
        }	
        protected internal Nullable<bool> _EsComprobanteRetencion;
        public virtual Nullable<bool> EsComprobanteRetencion
    	{
    	    get { return _EsComprobanteRetencion; }
    	    set { if (value != _EsComprobanteRetencion) { _EsComprobanteRetencion = value; OnPropertyChanged("EsComprobanteRetencion"); } }
        }	
        protected internal Nullable<bool> _EsTicketPuntoVenta;
        public virtual Nullable<bool> EsTicketPuntoVenta
    	{
    	    get { return _EsTicketPuntoVenta; }
    	    set { if (value != _EsTicketPuntoVenta) { _EsTicketPuntoVenta = value; OnPropertyChanged("EsTicketPuntoVenta"); } }
        }	
        protected internal Nullable<bool> _EsReciboPorHonorarios;
        public virtual Nullable<bool> EsReciboPorHonorarios
    	{
    	    get { return _EsReciboPorHonorarios; }
    	    set { if (value != _EsReciboPorHonorarios) { _EsReciboPorHonorarios = value; OnPropertyChanged("EsReciboPorHonorarios"); } }
        }	
        protected internal Nullable<bool> _EsComprobantePercepcion;
        public virtual Nullable<bool> EsComprobantePercepcion
    	{
    	    get { return _EsComprobantePercepcion; }
    	    set { if (value != _EsComprobantePercepcion) { _EsComprobantePercepcion = value; OnPropertyChanged("EsComprobantePercepcion"); } }
        }	
        protected internal Nullable<bool> _EsFacturaNegociable;
        public virtual Nullable<bool> EsFacturaNegociable
    	{
    	    get { return _EsFacturaNegociable; }
    	    set { if (value != _EsFacturaNegociable) { _EsFacturaNegociable = value; OnPropertyChanged("EsFacturaNegociable"); } }
        }	
        protected internal Nullable<bool> _EsNotaCredito;
        public virtual Nullable<bool> EsNotaCredito
    	{
    	    get { return _EsNotaCredito; }
    	    set { if (value != _EsNotaCredito) { _EsNotaCredito = value; OnPropertyChanged("EsNotaCredito"); } }
        }	
    
    
    
        public virtual ObservableCollection<Documento_Serie_BE> DocumentoSeriesGet(int paramMaxDepth = 1)
    	{
    		if (this.Id != null)
                return new ObservableCollection<Documento_Serie_BE>(new Documento_Serie_FL().LoadConvert(new Documento_Serie_FE() { Id = new Filter<Nullable<int>>(this.Id) }, paramMaxDepth));	
    
            return new ObservableCollection<Documento_Serie_BE>();
    	}
        public virtual ObservableCollection<Documento_Serie_BE> DocumentoSeriesLoad(int paramMaxDepth = 1)
    	{
    		return DocumentoSeries = DocumentoSeriesGet(paramMaxDepth);
    	}	
        public virtual ObservableCollection<Documento_Serie_BE> DocumentoSeries { get; set; }
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class Documentos_Venta_BE : Documentos_Venta_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class Documentos_Venta_DA : AccessEntityId
    {
    	public  Documentos_Venta_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new Documentos_Venta_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Documentos_Venta_DE be = (Documentos_Venta_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_nota_debito", System.Data.DbType.Boolean, be.EsNotaDebito, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "calcula_igv", System.Data.DbType.Boolean, be.CalculaIgv, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_comprobante_retencion", System.Data.DbType.Boolean, be.EsComprobanteRetencion, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_ticket_punto_venta", System.Data.DbType.Boolean, be.EsTicketPuntoVenta, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_recibo_por_honorarios", System.Data.DbType.Boolean, be.EsReciboPorHonorarios, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_comprobante_percepcion", System.Data.DbType.Boolean, be.EsComprobantePercepcion, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_factura_negociable", System.Data.DbType.Boolean, be.EsFacturaNegociable, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_nota_credito", System.Data.DbType.Boolean, be.EsNotaCredito, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            Documentos_Venta_DE be = (Documentos_Venta_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramReader[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramReader[TableColumn("abreviado")]);
    		be._CodigoTributario = Conversion.To<string>(paramReader[TableColumn("codigo_tributario")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramReader[TableColumn("activo")]);
    		be._EsNotaDebito = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_nota_debito")]);
    		be._CalculaIgv = Conversion.To<Nullable<bool>>(paramReader[TableColumn("calcula_igv")]);
    		be._EsComprobanteRetencion = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_comprobante_retencion")]);
    		be._EsTicketPuntoVenta = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_ticket_punto_venta")]);
    		be._EsReciboPorHonorarios = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_recibo_por_honorarios")]);
    		be._EsComprobantePercepcion = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_comprobante_percepcion")]);
    		be._EsFacturaNegociable = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_factura_negociable")]);
    		be._EsNotaCredito = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_nota_credito")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            Documentos_Venta_DE be = (Documentos_Venta_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramRow[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramRow[TableColumn("abreviado")]);
    		be._CodigoTributario = Conversion.To<string>(paramRow[TableColumn("codigo_tributario")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramRow[TableColumn("activo")]);
    		be._EsNotaDebito = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_nota_debito")]);
    		be._CalculaIgv = Conversion.To<Nullable<bool>>(paramRow[TableColumn("calcula_igv")]);
    		be._EsComprobanteRetencion = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_comprobante_retencion")]);
    		be._EsTicketPuntoVenta = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_ticket_punto_venta")]);
    		be._EsReciboPorHonorarios = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_recibo_por_honorarios")]);
    		be._EsComprobantePercepcion = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_comprobante_percepcion")]);
    		be._EsFacturaNegociable = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_factura_negociable")]);
    		be._EsNotaCredito = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_nota_credito")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            Documentos_Venta_DE be = (Documentos_Venta_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramParameters[TableParameter("nombre")].Value);
    		be._Abreviado = Conversion.To<string>(paramParameters[TableParameter("abreviado")].Value);
    		be._CodigoTributario = Conversion.To<string>(paramParameters[TableParameter("codigo_tributario")].Value);
    		be._Activo = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("activo")].Value);
    		be._EsNotaDebito = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_nota_debito")].Value);
    		be._CalculaIgv = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("calcula_igv")].Value);
    		be._EsComprobanteRetencion = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_comprobante_retencion")].Value);
    		be._EsTicketPuntoVenta = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_ticket_punto_venta")].Value);
    		be._EsReciboPorHonorarios = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_recibo_por_honorarios")].Value);
    		be._EsComprobantePercepcion = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_comprobante_percepcion")].Value);
    		be._EsFacturaNegociable = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_factura_negociable")].Value);
    		be._EsNotaCredito = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_nota_credito")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            Documentos_Venta_DE be = (Documentos_Venta_DE)paramDE;
    
    		be._Nombre = null;
    		be._Abreviado = null;
    		be._CodigoTributario = null;
    		be._Activo = null;
    		be._EsNotaDebito = null;
    		be._CalculaIgv = null;
    		be._EsComprobanteRetencion = null;
    		be._EsTicketPuntoVenta = null;
    		be._EsReciboPorHonorarios = null;
    		be._EsComprobantePercepcion = null;
    		be._EsFacturaNegociable = null;
    		be._EsNotaCredito = null;
      
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class Documentos_Venta_BA : Documentos_Venta_DA
    {
    	public  Documentos_Venta_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Documentos_Venta_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class Documentos_Venta_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new Documentos_Venta_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            Documentos_Venta_BE be = (Documentos_Venta_BE)paramDE;
    
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            Documentos_Venta_BE be = (Documentos_Venta_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
                if (new Documento_Serie_BL().Count(new Documento_Serie_BE() { Id = be.Id }) > 0)
                {
                    paramField = "DocumentoSerie";
    				paramMessage = LibraryFramework.V0006_TableDependencies;
    
                    return false;
                }
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		Documentos_Venta_BE be = (Documentos_Venta_BE)paramDE;
    
    		foreach (Documentos_Venta_BE e in new Documentos_Venta_FL().LoadConvert(new Documentos_Venta_FL().Convert(be), 1))
    		{
    			if (ret == 1)
    	            ret = new Documento_Serie_BL().Erase(new Documento_Serie_BE() { Id = e.Id }, false, paramIsSourceColumn); 
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class Documentos_Venta_BL : Documentos_Venta_DL
    {
        protected override Access GetDA()
        {
            return new Documentos_Venta_BA(TableName, ConnectionStringName);
        }	
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class Documentos_Venta_JE : EnumerateId
    {
        public virtual Filter<string> Nombre { get; set; }
        public virtual Filter<string> Abreviado { get; set; }
        public virtual Filter<string> CodigoTributario { get; set; }
        public virtual Filter<Nullable<bool>> Activo { get; set; }
        public virtual Filter<Nullable<bool>> EsNotaDebito { get; set; }
        public virtual Filter<Nullable<bool>> CalculaIgv { get; set; }
        public virtual Filter<Nullable<bool>> EsComprobanteRetencion { get; set; }
        public virtual Filter<Nullable<bool>> EsTicketPuntoVenta { get; set; }
        public virtual Filter<Nullable<bool>> EsReciboPorHonorarios { get; set; }
        public virtual Filter<Nullable<bool>> EsComprobantePercepcion { get; set; }
        public virtual Filter<Nullable<bool>> EsFacturaNegociable { get; set; }
        public virtual Filter<Nullable<bool>> EsNotaCredito { get; set; }
    
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class Documentos_Venta_FE : Documentos_Venta_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class Documentos_Venta_JA : AccessEnumerateId
    {	
    	public  Documentos_Venta_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Documentos_Venta_DE();
        }
    	protected override Access GetDA()
        {
            return new Documentos_Venta_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Documentos_Venta_JE be = (Documentos_Venta_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_nota_debito", System.Data.DbType.Boolean, be.EsNotaDebito, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "calcula_igv", System.Data.DbType.Boolean, be.CalculaIgv, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_comprobante_retencion", System.Data.DbType.Boolean, be.EsComprobanteRetencion, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_ticket_punto_venta", System.Data.DbType.Boolean, be.EsTicketPuntoVenta, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_recibo_por_honorarios", System.Data.DbType.Boolean, be.EsReciboPorHonorarios, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_comprobante_percepcion", System.Data.DbType.Boolean, be.EsComprobantePercepcion, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_factura_negociable", System.Data.DbType.Boolean, be.EsFacturaNegociable, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_nota_credito", System.Data.DbType.Boolean, be.EsNotaCredito, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Documentos_Venta_FE be = (Documentos_Venta_FE)paramDE;
    		
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		Documentos_Venta_FE be = (Documentos_Venta_FE)paramDE;	
    
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class Documentos_Venta_FA : Documentos_Venta_JA
    {	
    	public  Documentos_Venta_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Documentos_Venta_BE();
        }
    	protected override Access GetDA()
        {
            return new Documentos_Venta_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class Documentos_Venta_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new Documentos_Venta_JA(TableName, ConnectionStringName);
        }
    	
    	public ObservableCollection<Documentos_Venta_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return new ObservableCollection<Documentos_Venta_BE>(Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as Documentos_Venta_BE));
        }
    	public Documentos_Venta_FE Convert(Documentos_Venta_BE paramDE)
        {
            Documentos_Venta_FE be = new Documentos_Venta_FE();
    
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
    		be.Nombre = new Filter<string>(paramDE.Nombre);
    		be.Abreviado = new Filter<string>(paramDE.Abreviado);
    		be.CodigoTributario = new Filter<string>(paramDE.CodigoTributario);
    		be.Activo = new Filter<Nullable<bool>>(paramDE.Activo);
    		be.EsNotaDebito = new Filter<Nullable<bool>>(paramDE.EsNotaDebito);
    		be.CalculaIgv = new Filter<Nullable<bool>>(paramDE.CalculaIgv);
    		be.EsComprobanteRetencion = new Filter<Nullable<bool>>(paramDE.EsComprobanteRetencion);
    		be.EsTicketPuntoVenta = new Filter<Nullable<bool>>(paramDE.EsTicketPuntoVenta);
    		be.EsReciboPorHonorarios = new Filter<Nullable<bool>>(paramDE.EsReciboPorHonorarios);
    		be.EsComprobantePercepcion = new Filter<Nullable<bool>>(paramDE.EsComprobantePercepcion);
    		be.EsFacturaNegociable = new Filter<Nullable<bool>>(paramDE.EsFacturaNegociable);
    		be.EsNotaCredito = new Filter<Nullable<bool>>(paramDE.EsNotaCredito);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class Documentos_Venta_FL : Documentos_Venta_JL
    {
    	protected override Access GetDA()
        {
            return new Documentos_Venta_FA(TableName, ConnectionStringName);
        }
    }
}

