//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class DocumentoSerie_DE : EntityId
    {
    	//Fields
        protected internal string _Serie;
        public virtual string Serie
    	{
    	    get { return _Serie; }
    	    set { if (value != _Serie) { _Serie = value; OnPropertyChanged("Serie"); } }
        }	
        protected internal Nullable<int> _NumeroActual;
        public virtual Nullable<int> NumeroActual
    	{
    	    get { return _NumeroActual; }
    	    set { if (value != _NumeroActual) { _NumeroActual = value; OnPropertyChanged("NumeroActual"); } }
        }	
        protected internal Nullable<bool> _EsElectronico;
        public virtual Nullable<bool> EsElectronico
    	{
    	    get { return _EsElectronico; }
    	    set { if (value != _EsElectronico) { _EsElectronico = value; OnPropertyChanged("EsElectronico"); } }
        }	
    
    	//ForeignKeys
    	protected internal Nullable<int> _IdDocumentoVenta;
    	public virtual Nullable<int> IdDocumentoVenta
    	{
    		get
    		{
    			return _IdDocumentoVenta;
    		}
    		set
    		{
                if (value != _IdDocumentoVenta) 
    			{
    				_IdDocumentoVenta = value;
    				
    				if (_IdDocumentoVenta == null) DocumentosVenta = null;			
    												
    				OnPropertyChanged("IdDocumentoVenta");
    			}		
    		}
    	}	
    
    	//Parents
    	protected internal DocumentosVenta_BE _DocumentosVenta;
        public virtual DocumentosVenta_BE DocumentosVenta
    	{
            get 
            {
    			if (IdDocumentoVenta != null)
    			{
    				if (_DocumentosVenta == null) _DocumentosVenta = new DocumentosVenta_BE();
    			
    				if (!_DocumentosVenta.Loaded)
    				{
    					_DocumentosVenta.Id = IdDocumentoVenta;				
    					new DocumentosVenta_BL().Load(_DocumentosVenta);
    				}
    			}	
    			
    			return _DocumentosVenta;
            } 
    		set
    		{
                if (value != _DocumentosVenta) 
    			{
    				if (_DocumentosVenta != null)
    					_DocumentosVenta.DocumentoSeries.Remove((DocumentoSerie_BE)this);
    				if (value != null)
    					value.DocumentoSeries.Add((DocumentoSerie_BE)this);
    
    				_DocumentosVenta = value;	
    				
    				OnPropertyChanged("DocumentosVenta");
    			}
    		}
    	}
    
    	//Childs
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class DocumentoSerie_BE : DocumentoSerie_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class DocumentoSerie_DA : AccessEntityId
    {
    	public  DocumentoSerie_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new DocumentoSerie_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            DocumentoSerie_DE be = (DocumentoSerie_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "serie", System.Data.DbType.String, be.Serie, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<int>>(fields, "numero_actual", System.Data.DbType.Int32, be.NumeroActual, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_electronico", System.Data.DbType.Boolean, be.EsElectronico, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<int>>(fields, "id_documento_venta", System.Data.DbType.Int32, be.IdDocumentoVenta, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            DocumentoSerie_DE be = (DocumentoSerie_DE)paramDE;
    
    		be._Serie = Conversion.To<string>(paramReader[TableColumn("serie")]);
    		be._NumeroActual = Conversion.To<Nullable<int>>(paramReader[TableColumn("numero_actual")]);
    		be._EsElectronico = Conversion.To<Nullable<bool>>(paramReader[TableColumn("es_electronico")]);
    		be._IdDocumentoVenta = Conversion.To<Nullable<int>>(paramReader[TableColumn("id_documento_venta")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            DocumentoSerie_DE be = (DocumentoSerie_DE)paramDE;
    
    		be._Serie = Conversion.To<string>(paramRow[TableColumn("serie")]);
    		be._NumeroActual = Conversion.To<Nullable<int>>(paramRow[TableColumn("numero_actual")]);
    		be._EsElectronico = Conversion.To<Nullable<bool>>(paramRow[TableColumn("es_electronico")]);
    		be._IdDocumentoVenta = Conversion.To<Nullable<int>>(paramRow[TableColumn("id_documento_venta")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            DocumentoSerie_DE be = (DocumentoSerie_DE)paramDE;
    
    		be._Serie = Conversion.To<string>(paramParameters[TableParameter("serie")].Value);
    		be._NumeroActual = Conversion.To<Nullable<int>>(paramParameters[TableParameter("numero_actual")].Value);
    		be._EsElectronico = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("es_electronico")].Value);
    		be._IdDocumentoVenta = Conversion.To<Nullable<int>>(paramParameters[TableParameter("id_documento_venta")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            DocumentoSerie_DE be = (DocumentoSerie_DE)paramDE;
    
    		be._Serie = null;
    		be._NumeroActual = null;
    		be._EsElectronico = null;
    		be._IdDocumentoVenta = null;
      
    		be._DocumentosVenta = null;
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class DocumentoSerie_BA : DocumentoSerie_DA
    {
    	public  DocumentoSerie_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new DocumentoSerie_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class DocumentoSerie_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new DocumentoSerie_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            DocumentoSerie_BE be = (DocumentoSerie_BE)paramDE;
    
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            DocumentoSerie_BE be = (DocumentoSerie_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		DocumentoSerie_BE be = (DocumentoSerie_BE)paramDE;
    
    		foreach (DocumentoSerie_BE e in new DocumentoSerie_FL().LoadConvert(new DocumentoSerie_FL().Convert(be), 1))
    		{
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    	
    	protected override byte SaveParent(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            DocumentoSerie_BE be = (DocumentoSerie_BE)paramDE;
    
            byte ret = 1;
    
    		if (ret == 1)
                ret = new DocumentosVenta_BL().Save(be.DocumentosVenta, paramStatus, paramCheckKeyEmpty, paramIsSourceColumn);
    				
            if (ret == 1)
            {		
    			if (be.DocumentosVenta != null) be.IdDocumentoVenta = be.DocumentosVenta.Id;		
    		}
    
            return ret;
        }
        protected override byte SaveDetails(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            DocumentoSerie_BE be = (DocumentoSerie_BE)paramDE;
    
            byte ret = 1;
    
            if (ret == 1)
            {        
    		} 
    		
            if (ret == 1)
            {		}		
            
            return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class DocumentoSerie_BL : DocumentoSerie_DL
    {
        protected override Access GetDA()
        {
            return new DocumentoSerie_BA(TableName, ConnectionStringName);
        }		
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class DocumentoSerie_JE : EnumerateId
    {
        public virtual Filter<string> Serie { get; set; }
        public virtual Filter<Nullable<int>> NumeroActual { get; set; }
        public virtual Filter<Nullable<bool>> EsElectronico { get; set; }
        public virtual Filter<Nullable<int>> IdDocumentoVenta { get; set; }
    
    	protected DocumentosVenta_FE _DocumentosVenta;
        public DocumentosVenta_FE DocumentosVenta
    	{
            get 
            {
                _DocumentosVenta = _DocumentosVenta ?? new DocumentosVenta_FE();
                return _DocumentosVenta;
            } 
    		set
    		{
    			_DocumentosVenta = value;
    		}
    	}
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class DocumentoSerie_FE : DocumentoSerie_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class DocumentoSerie_JA : AccessEnumerateId
    {	
    	public  DocumentoSerie_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new DocumentoSerie_DE();
        }
    	protected override Access GetDA()
        {
            return new DocumentoSerie_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            DocumentoSerie_JE be = (DocumentoSerie_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "serie", System.Data.DbType.String, be.Serie, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<int>>(fields, "numero_actual", System.Data.DbType.Int32, be.NumeroActual, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "es_electronico", System.Data.DbType.Boolean, be.EsElectronico, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<int>>(fields, "id_documento_venta", System.Data.DbType.Int32, be.IdDocumentoVenta, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            DocumentoSerie_FE be = (DocumentoSerie_FE)paramDE;
    		
    		foreach (Field f in new DocumentosVenta_FL().GetFieldsJoin(be.DocumentosVenta, paramDepth, paramMaxDepth, paramIsSourceColumn, paramTableAlias + "__documentos_venta"))
        		paramFields.Add(f);
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		DocumentoSerie_FE be = (DocumentoSerie_FE)paramDE;	
    	
    		paramTables += new DocumentosVenta_FL().GetTablesJoin(be.DocumentosVenta, paramDepth, paramMaxDepth, paramIsSourceColumn, paramTableAlias, paramTableAlias + "__documentos_venta", new Dictionary<string, string>() { { "id_documento_venta", "id" } });
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class DocumentoSerie_FA : DocumentoSerie_JA
    {	
    	public  DocumentoSerie_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new DocumentoSerie_BE();
        }
    	protected override Access GetDA()
        {
            return new DocumentoSerie_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class DocumentoSerie_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new DocumentoSerie_JA(TableName, ConnectionStringName);
        }
    	
    	public List<DocumentoSerie_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as DocumentoSerie_BE);
        }
    	public DocumentoSerie_FE Convert(DocumentoSerie_BE paramDE)
        {
            DocumentoSerie_FE be = new DocumentoSerie_FE();
    
    		be.Serie = new Filter<string>(paramDE.Serie);
    		be.NumeroActual = new Filter<Nullable<int>>(paramDE.NumeroActual);
    		be.EsElectronico = new Filter<Nullable<bool>>(paramDE.EsElectronico);
    		be.IdDocumentoVenta = new Filter<Nullable<int>>(paramDE.IdDocumentoVenta);
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class DocumentoSerie_FL : DocumentoSerie_JL
    {
    	protected override Access GetDA()
        {
            return new DocumentoSerie_FA(TableName, ConnectionStringName);
        }
    }
}

