//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class Moneda_DE : EntityId
    {
    	//Fields
        protected internal string _CodigoTributario;
        public virtual string CodigoTributario
    	{
    	    get { return _CodigoTributario; }
    	    set { if (value != _CodigoTributario) { _CodigoTributario = value; OnPropertyChanged("CodigoTributario"); } }
        }	
        protected internal string _Nombre;
        public virtual string Nombre
    	{
    	    get { return _Nombre; }
    	    set { if (value != _Nombre) { _Nombre = value; OnPropertyChanged("Nombre"); } }
        }	
        protected internal string _Abreviado;
        public virtual string Abreviado
    	{
    	    get { return _Abreviado; }
    	    set { if (value != _Abreviado) { _Abreviado = value; OnPropertyChanged("Abreviado"); } }
        }	
        protected internal Nullable<bool> _Activo;
        public virtual Nullable<bool> Activo
    	{
    	    get { return _Activo; }
    	    set { if (value != _Activo) { _Activo = value; OnPropertyChanged("Activo"); } }
        }	
    
    	//ForeignKeys
    
    	//Parents
    
    	//Childs
        void OnCollectionChanged_TipoCambioOrigenes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.Action == NotifyCollectionChangedAction.Add)
            {
                foreach (TipoCambio_BE item in e.NewItems)
    			{
    				item.IdMonedaOrigen = this.Id;			
    			}
            }
            if (e.Action == NotifyCollectionChangedAction.Remove)
            {
                foreach (TipoCambio_BE item in e.OldItems)
    			{
    				item.IdMonedaOrigen = null;			
    			}
            }
        }
        protected internal virtual ObservableCollection<TipoCambio_BE> _TipoCambioOrigenes { get; set; }
        public virtual ObservableCollection<TipoCambio_BE> TipoCambioOrigenes 
    	{ 
    		get
    		{
                if (_TipoCambioOrigenes == null)
                    TipoCambioOrigenes = TipoCambioOrigenes_New(new List<TipoCambio_BE>());
    
                return _TipoCambioOrigenes;		
    		}
    		set
    		{
    			_TipoCambioOrigenes = value;	
    			
    			OnPropertyChanged("TipoCambioOrigenes");
    			
    			_TipoCambioOrigenes.CollectionChanged += this.OnCollectionChanged_TipoCambioOrigenes;
    		}
    	}
    	public virtual ObservableCollection<TipoCambio_BE> TipoCambioOrigenes_New(List<TipoCambio_BE> paramList)
        {
            return new ObservableCollection<TipoCambio_BE>(paramList);
        }	
        public virtual ObservableCollection<TipoCambio_BE> TipoCambioOrigenes_Load(int paramMaxDepth = 1)
    	{
    		return TipoCambioOrigenes = TipoCambioOrigenes_Get(paramMaxDepth);
    	}	
    	public virtual ObservableCollection<TipoCambio_BE> TipoCambioOrigenes_Get(int paramMaxDepth = 1)
    	{
    		return TipoCambioOrigenes_New(this.Exists ? new TipoCambio_FL().LoadConvert(new TipoCambio_FE() { IdMonedaOrigen = new Filter<Nullable<int>>(this.Id) }, paramMaxDepth) : new List<TipoCambio_BE>());	
    	}
        void OnCollectionChanged_TipoCambioDestinos(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.Action == NotifyCollectionChangedAction.Add)
            {
                foreach (TipoCambio_BE item in e.NewItems)
    			{
    				item.IdMonedaDestino = this.Id;			
    			}
            }
            if (e.Action == NotifyCollectionChangedAction.Remove)
            {
                foreach (TipoCambio_BE item in e.OldItems)
    			{
    				item.IdMonedaDestino = null;			
    			}
            }
        }
        protected internal virtual ObservableCollection<TipoCambio_BE> _TipoCambioDestinos { get; set; }
        public virtual ObservableCollection<TipoCambio_BE> TipoCambioDestinos 
    	{ 
    		get
    		{
                if (_TipoCambioDestinos == null)
                    TipoCambioDestinos = TipoCambioDestinos_New(new List<TipoCambio_BE>());
    
                return _TipoCambioDestinos;		
    		}
    		set
    		{
    			_TipoCambioDestinos = value;	
    			
    			OnPropertyChanged("TipoCambioDestinos");
    			
    			_TipoCambioDestinos.CollectionChanged += this.OnCollectionChanged_TipoCambioDestinos;
    		}
    	}
    	public virtual ObservableCollection<TipoCambio_BE> TipoCambioDestinos_New(List<TipoCambio_BE> paramList)
        {
            return new ObservableCollection<TipoCambio_BE>(paramList);
        }	
        public virtual ObservableCollection<TipoCambio_BE> TipoCambioDestinos_Load(int paramMaxDepth = 1)
    	{
    		return TipoCambioDestinos = TipoCambioDestinos_Get(paramMaxDepth);
    	}	
    	public virtual ObservableCollection<TipoCambio_BE> TipoCambioDestinos_Get(int paramMaxDepth = 1)
    	{
    		return TipoCambioDestinos_New(this.Exists ? new TipoCambio_FL().LoadConvert(new TipoCambio_FE() { IdMonedaDestino = new Filter<Nullable<int>>(this.Id) }, paramMaxDepth) : new List<TipoCambio_BE>());	
    	}
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class Moneda_BE : Moneda_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class Moneda_DA : AccessEntityId
    {
    	public  Moneda_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new Moneda_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Moneda_DE be = (Moneda_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            Moneda_DE be = (Moneda_DE)paramDE;
    
    		be._CodigoTributario = Conversion.To<string>(paramReader[TableColumn("codigo_tributario")]);
    		be._Nombre = Conversion.To<string>(paramReader[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramReader[TableColumn("abreviado")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramReader[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            Moneda_DE be = (Moneda_DE)paramDE;
    
    		be._CodigoTributario = Conversion.To<string>(paramRow[TableColumn("codigo_tributario")]);
    		be._Nombre = Conversion.To<string>(paramRow[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramRow[TableColumn("abreviado")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramRow[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            Moneda_DE be = (Moneda_DE)paramDE;
    
    		be._CodigoTributario = Conversion.To<string>(paramParameters[TableParameter("codigo_tributario")].Value);
    		be._Nombre = Conversion.To<string>(paramParameters[TableParameter("nombre")].Value);
    		be._Abreviado = Conversion.To<string>(paramParameters[TableParameter("abreviado")].Value);
    		be._Activo = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("activo")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            Moneda_DE be = (Moneda_DE)paramDE;
    
    		be._CodigoTributario = null;
    		be._Nombre = null;
    		be._Abreviado = null;
    		be._Activo = null;
      
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class Moneda_BA : Moneda_DA
    {
    	public  Moneda_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Moneda_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class Moneda_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new Moneda_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            Moneda_BE be = (Moneda_BE)paramDE;
    
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            Moneda_BE be = (Moneda_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
                if (new TipoCambio_BL().Count(new TipoCambio_BE() { IdMonedaOrigen = be.Id }) > 0)
                {
                    paramField = "TipoCambio";
    				paramMessage = LibraryFramework.V0006_TableDependencies;
    
                    return false;
                }
                if (new TipoCambio_BL().Count(new TipoCambio_BE() { IdMonedaDestino = be.Id }) > 0)
                {
                    paramField = "TipoCambio";
    				paramMessage = LibraryFramework.V0006_TableDependencies;
    
                    return false;
                }
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		Moneda_BE be = (Moneda_BE)paramDE;
    
    		foreach (Moneda_BE e in new Moneda_FL().LoadConvert(new Moneda_FL().Convert(be), 1))
    		{
    			if (ret == 1)
    	            ret = new TipoCambio_BL().Erase(new TipoCambio_BE() { IdMonedaOrigen = e.Id }, false, paramIsSourceColumn); 
    			if (ret == 1)
    	            ret = new TipoCambio_BL().Erase(new TipoCambio_BE() { IdMonedaDestino = e.Id }, false, paramIsSourceColumn); 
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    	
    	protected override byte SaveParent(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            Moneda_BE be = (Moneda_BE)paramDE;
    
            byte ret = 1;
    
    				
            if (ret == 1)
            {		
    		}
    
            return ret;
        }
        protected override byte SaveDetails(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            Moneda_BE be = (Moneda_BE)paramDE;
    
            byte ret = 1;
    
            if (ret == 1)
            {		
    			foreach (TipoCambio_BE beTipoCambioOrigen in be.TipoCambioOrigenes)
    					beTipoCambioOrigen.IdMonedaOrigen = be.Id;		
    			foreach (TipoCambio_BE beTipoCambioDestino in be.TipoCambioDestinos)
    					beTipoCambioDestino.IdMonedaDestino = be.Id;        
    		} 
    		
            if (ret == 1)
            {		
    			foreach (TipoCambio_BE beTipoCambioOrigen in be.TipoCambioOrigenes)
                    if (ret == 1)
                        ret = new TipoCambio_BL().Save(beTipoCambioOrigen, paramStatus, paramCheckKeyEmpty, paramIsSourceColumn);
    		
    			foreach (TipoCambio_BE beTipoCambioDestino in be.TipoCambioDestinos)
                    if (ret == 1)
                        ret = new TipoCambio_BL().Save(beTipoCambioDestino, paramStatus, paramCheckKeyEmpty, paramIsSourceColumn);
    		}		
            
            return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class Moneda_BL : Moneda_DL
    {
        protected override Access GetDA()
        {
            return new Moneda_BA(TableName, ConnectionStringName);
        }		
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class Moneda_JE : EnumerateId
    {
        public virtual Filter<string> CodigoTributario { get; set; }
        public virtual Filter<string> Nombre { get; set; }
        public virtual Filter<string> Abreviado { get; set; }
        public virtual Filter<Nullable<bool>> Activo { get; set; }
    
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class Moneda_FE : Moneda_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class Moneda_JA : AccessEnumerateId
    {	
    	public  Moneda_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Moneda_DE();
        }
    	protected override Access GetDA()
        {
            return new Moneda_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Moneda_JE be = (Moneda_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            Moneda_FE be = (Moneda_FE)paramDE;
    		
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		Moneda_FE be = (Moneda_FE)paramDE;	
    
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class Moneda_FA : Moneda_JA
    {	
    	public  Moneda_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new Moneda_BE();
        }
    	protected override Access GetDA()
        {
            return new Moneda_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class Moneda_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new Moneda_JA(TableName, ConnectionStringName);
        }
    	
    	public List<Moneda_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as Moneda_BE);
        }
    	public Moneda_FE Convert(Moneda_BE paramDE)
        {
            Moneda_FE be = new Moneda_FE();
    
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
    		be.CodigoTributario = new Filter<string>(paramDE.CodigoTributario);
    		be.Nombre = new Filter<string>(paramDE.Nombre);
    		be.Abreviado = new Filter<string>(paramDE.Abreviado);
    		be.Activo = new Filter<Nullable<bool>>(paramDE.Activo);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class Moneda_FL : Moneda_JL
    {
    	protected override Access GetDA()
        {
            return new Moneda_FA(TableName, ConnectionStringName);
        }
    }
}

