//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Library.Common.Data;
using Library.Framework;
using Library.Framework.Layers;
using Library.Framework.Data;

using Facel.Data.Entities;
using Facel.Data.Accesses;
using Facel.Data.Logics;
using Facel.Business.Entities;
using Facel.Business.Accesses;
using Facel.Business.Logics;
using Facel.Join.Entities;
using Facel.Join.Accesses;
using Facel.Join.Logics;
using Facel.Filter.Entities;
using Facel.Filter.Accesses;
using Facel.Filter.Logics;
using Facel.Main;


//DataEntity
namespace Facel.Data.Entities
{
    [Serializable]
    public partial class UnidadMedida_DE : EntityId
    {
    	//Fields
        protected internal string _Nombre;
        public virtual string Nombre
    	{
    	    get { return _Nombre; }
    	    set { if (value != _Nombre) { _Nombre = value; OnPropertyChanged("Nombre"); } }
        }	
        protected internal string _Abreviado;
        public virtual string Abreviado
    	{
    	    get { return _Abreviado; }
    	    set { if (value != _Abreviado) { _Abreviado = value; OnPropertyChanged("Abreviado"); } }
        }	
        protected internal string _CodigoTributario;
        public virtual string CodigoTributario
    	{
    	    get { return _CodigoTributario; }
    	    set { if (value != _CodigoTributario) { _CodigoTributario = value; OnPropertyChanged("CodigoTributario"); } }
        }	
        protected internal Nullable<bool> _Activo;
        public virtual Nullable<bool> Activo
    	{
    	    get { return _Activo; }
    	    set { if (value != _Activo) { _Activo = value; OnPropertyChanged("Activo"); } }
        }	
    
    	//ForeignKeys
    
    	//Parents
    
    	//Childs
    }
}

namespace Facel.Business.Entities
{
    [Serializable]
    public partial class UnidadMedida_BE : UnidadMedida_DE
    {
    }
}

//DataAccess
namespace Facel.Data.Accesses
{
    [Serializable]
    public partial class UnidadMedida_DA : AccessEntityId
    {
    	public  UnidadMedida_DA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    
        protected override Entity GetDE()
        {
            return new UnidadMedida_DE();
        }
    
        public override List<Field> GetFieldsData(Entity paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            UnidadMedida_DE be = (UnidadMedida_DE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    
        protected override Entity LoadDataReader(DbDataReader paramReader, Entity paramDE)
    	{
            UnidadMedida_DE be = (UnidadMedida_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramReader[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramReader[TableColumn("abreviado")]);
    		be._CodigoTributario = Conversion.To<string>(paramReader[TableColumn("codigo_tributario")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramReader[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataRow(DataRow paramRow, Entity paramDE)
    	{
            UnidadMedida_DE be = (UnidadMedida_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramRow[TableColumn("nombre")]);
    		be._Abreviado = Conversion.To<string>(paramRow[TableColumn("abreviado")]);
    		be._CodigoTributario = Conversion.To<string>(paramRow[TableColumn("codigo_tributario")]);
    		be._Activo = Conversion.To<Nullable<bool>>(paramRow[TableColumn("activo")]);
      
            return be;
    	}
        protected override Entity LoadDataParameters(DbParameterCollection paramParameters, Entity paramDE)
    	{
            UnidadMedida_DE be = (UnidadMedida_DE)paramDE;
    
    		be._Nombre = Conversion.To<string>(paramParameters[TableParameter("nombre")].Value);
    		be._Abreviado = Conversion.To<string>(paramParameters[TableParameter("abreviado")].Value);
    		be._CodigoTributario = Conversion.To<string>(paramParameters[TableParameter("codigo_tributario")].Value);
    		be._Activo = Conversion.To<Nullable<bool>>(paramParameters[TableParameter("activo")].Value);
      
            return be;
    	}
    
        protected override Entity ClearData(Entity paramDE)
        {
            UnidadMedida_DE be = (UnidadMedida_DE)paramDE;
    
    		be._Nombre = null;
    		be._Abreviado = null;
    		be._CodigoTributario = null;
    		be._Activo = null;
      
    
            return be;
        }
    
    }
}

namespace Facel.Business.Accesses
{
    [Serializable]
    public partial class UnidadMedida_BA : UnidadMedida_DA
    {
    	public  UnidadMedida_BA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new UnidadMedida_BE();
        }
    }
}

//DataLogic
namespace Facel.Data.Logics
{
    [Serializable]
    public partial class UnidadMedida_DL : LogicEntity
    {
        protected override Access GetDA()
        {
            return new UnidadMedida_DA(TableName, ConnectionStringName);
        }
    	
    	protected override bool ValidateInsertModel(Entity paramDE, ref string paramField, ref string paramMessage)
        {
            UnidadMedida_BE be = (UnidadMedida_BE)paramDE;
    
      
    		return base.ValidateInsertModel(paramDE, ref paramField, ref paramMessage);
        }
    	protected override bool ValidateDeleteModel(Entity paramDE, ref string paramField, ref string paramMessage, bool paramValidateCascadeIntegrity = true)
        {
            UnidadMedida_BE be = (UnidadMedida_BE)paramDE;
    
            if (paramValidateCascadeIntegrity)
            {
            }
    			     
            return base.ValidateDeleteModel(paramDE, ref paramField, ref paramMessage, paramValidateCascadeIntegrity);
        }
    	
    	public override byte EraseModel(Entity paramDE, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            byte ret = 1;
    
    		UnidadMedida_BE be = (UnidadMedida_BE)paramDE;
    
    		foreach (UnidadMedida_BE e in new UnidadMedida_FL().LoadConvert(new UnidadMedida_FL().Convert(be), 1))
    		{
     		}
    		
    		if (ret == 1)
                ret = base.EraseModel(paramDE, paramCheckKeyEmpty, paramIsSourceColumn);
            
    		return ret;
        }	
    	
    	protected override byte SaveParent(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            UnidadMedida_BE be = (UnidadMedida_BE)paramDE;
    
            byte ret = 1;
    
    				
            if (ret == 1)
            {		
    		}
    
            return ret;
        }
        protected override byte SaveDetails(Entity paramDE, SaveStatus paramStatus, bool paramCheckKeyEmpty = true, bool paramIsSourceColumn = false)
        {
            UnidadMedida_BE be = (UnidadMedida_BE)paramDE;
    
            byte ret = 1;
    
            if (ret == 1)
            {        
    		} 
    		
            if (ret == 1)
            {		}		
            
            return ret;
        }	
    }
}

namespace Facel.Business.Logics
{
    [Serializable]
    public partial class UnidadMedida_BL : UnidadMedida_DL
    {
        protected override Access GetDA()
        {
            return new UnidadMedida_BA(TableName, ConnectionStringName);
        }		
    }
    
}

//JoinEntities
namespace Facel.Join.Entities
{
    [Serializable]
    public partial class UnidadMedida_JE : EnumerateId
    {
        public virtual Filter<string> Nombre { get; set; }
        public virtual Filter<string> Abreviado { get; set; }
        public virtual Filter<string> CodigoTributario { get; set; }
        public virtual Filter<Nullable<bool>> Activo { get; set; }
    
    }
}

namespace Facel.Filter.Entities
{
    [Serializable]
    public partial class UnidadMedida_FE : UnidadMedida_JE
    {
    }
}


//JoinAccess
namespace Facel.Join.Accesses
{
    [Serializable]
    public partial class UnidadMedida_JA : AccessEnumerateId
    {	
    	public  UnidadMedida_JA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new UnidadMedida_DE();
        }
    	protected override Access GetDA()
        {
            return new UnidadMedida_DA(TableName, ConnectionStringName);
        }
    	
    	public override List<Field> GetFieldsData(Enumerate paramDE, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            UnidadMedida_JE be = (UnidadMedida_JE)paramDE;
    
            List<Field> fields = new List<Field>();
    
            fields = AddField<string>(fields, "nombre", System.Data.DbType.String, be.Nombre, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "abreviado", System.Data.DbType.String, be.Abreviado, paramIsSourceColumn, paramTableAlias);
            fields = AddField<string>(fields, "codigo_tributario", System.Data.DbType.String, be.CodigoTributario, paramIsSourceColumn, paramTableAlias);
            fields = AddField<Nullable<bool>>(fields, "activo", System.Data.DbType.Boolean, be.Activo, paramIsSourceColumn, paramTableAlias);
            
    		return fields;
        }
    	
    	protected override List<Field> GetFieldsJoin(List<Field> paramFields, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "")
        {
            UnidadMedida_FE be = (UnidadMedida_FE)paramDE;
    		
            
    		return paramFields;
    	}
    	protected override string GetTablesJoin(string paramTables, Enumerate paramDE, int paramDepth, int paramMaxDepth = 0, bool paramIsSourceColumn = false, 
    		string paramTableAlias = "",
    		Dictionary<string, string> paramFieldsJoin = null)
        {
    		UnidadMedida_FE be = (UnidadMedida_FE)paramDE;	
    
    
    		return paramTables;
    	}	
    		
    }
}

namespace Facel.Filter.Accesses
{
    [Serializable]
    public partial class UnidadMedida_FA : UnidadMedida_JA
    {	
    	public  UnidadMedida_FA(string paramTableName, string paramConnectionStringName)
            : base(paramTableName, paramConnectionStringName)
    	{
    	}
    	
    	protected override Entity GetDE()
        {
            return new UnidadMedida_BE();
        }
    	protected override Access GetDA()
        {
            return new UnidadMedida_BA(TableName, ConnectionStringName);
        }
    }
}


//JoinLogic
namespace Facel.Join.Logics
{
    [Serializable]
    public partial class UnidadMedida_JL : LogicEnumerate
    {
    	protected override Access GetDA()
        {
            return new UnidadMedida_JA(TableName, ConnectionStringName);
        }
    	
    	public List<UnidadMedida_BE> LoadConvert(Enumerate paramDE, int paramMaxDepth = 0, TypeLoad paramTypeLoad = TypeLoad.DataReader, bool paramIsSourceColumn = false,
                int paramTop = 0,
    			int paramRowFrom = 0, int paramRowTo = 0)
        {
        	return Load(paramDE, paramMaxDepth, paramTypeLoad, paramIsSourceColumn,
                    paramTop,
    				paramRowFrom, paramRowTo).ConvertAll(x => x as UnidadMedida_BE);
        }
    	public UnidadMedida_FE Convert(UnidadMedida_BE paramDE)
        {
            UnidadMedida_FE be = new UnidadMedida_FE();
    
    		be.Id = new Filter<Nullable<int>>(paramDE.Id);
    		be.Nombre = new Filter<string>(paramDE.Nombre);
    		be.Abreviado = new Filter<string>(paramDE.Abreviado);
    		be.CodigoTributario = new Filter<string>(paramDE.CodigoTributario);
    		be.Activo = new Filter<Nullable<bool>>(paramDE.Activo);
      
            return be;
        }	
    }
}

namespace Facel.Filter.Logics
{
    [Serializable]
    public partial class UnidadMedida_FL : UnidadMedida_JL
    {
    	protected override Access GetDA()
        {
            return new UnidadMedida_FA(TableName, ConnectionStringName);
        }
    }
}

